Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
choco upgrade all -y
choco install powershell-core --pre  -y 
choco install dotnetcore-sdk --pre  -y
choco install dotnetcore-runtime --pre  -y
choco install keepass -y
choco install keepass-plugin-keeagent -y
choco install geforce-experience -y
choco install dropbox -y
choco install spideroakone -y
choco install git -y
choco install tortoisegit -y
choco install nodejs -y
choco install yarn -y
choco install steam -y
choco install brave -y
choco install googlechrome  -y
choco install firefox -y
choco install discord -y
choco install spotify -y
choco install origin  -y
choco install krita -y
choco install audacity -y
choco install neo4j-community  -y
choco install openshot -y
choco install idlemaster -y
choco install uplay -y
choco install inkscape -y
choco install obs-studio -y
choco install gimp -y
choco install filezilla  -y
choco install goggalaxy -y
choco install virtualbox -y
choco install paint.net  -y
choco install blender -y
choco install vagrant -y
choco install peazip -y
choco install packer -y
choco install minikube  -y
choco install docker-kitematic -y
choco install kubernetes-cli -y
choco install slack -y
choco install xming -y
choco install putty -y
choco install puppet -y
choco install docker -y
choco install greenshot -y
choco install cmake.install -y
choco install authy-desktop -y
choco install visualstudiocode -y
choco install vscode-powershell -y
choco install visualstudio2017community -y
choco install paint.net -y 
choco install unity -y 
choco install epicgameslauncher -y
choco install minecraft -y
choco install mremoteng -y
choco install winscp -y
choco install tor-browser -y
choco install libreoffice -y
choco install androidstudio -y
choco install filebeat -y
choco install deluge -y